<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TeyPdfCad.AutoCAD.Bridge.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TeyPdfCad.Core/TeyPdfCad.Core.csproj" />
  </ItemGroup>
</Project>
