<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TeyPdfCad.Core/TeyPdfCad.Core.csproj" />
    <ProjectReference Include="../TeyPdfCad.Pdf/TeyPdfCad.Pdf.csproj" />
    <ProjectReference Include="../TeyPdfCad.Dwg/TeyPdfCad.Dwg.csproj" />
  </ItemGroup>
</Project>
