<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(TeyAutoCadTargetFramework)' == ''">net8.0</TargetFramework>
    <TargetFramework Condition="'$(TeyAutoCadTargetFramework)' != ''">$(TeyAutoCadTargetFramework)</TargetFramework>
    <RootNamespace>TeyPdfCad.AutoCAD</RootNamespace>
    <AssemblyName>TeyPdfCad.AutoCAD</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AutoCADApiVersion Condition="'$(AutoCADApiVersion)' == ''">25.1.0</AutoCADApiVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TeyPdfCad.Core/TeyPdfCad.Core.csproj" />
    <PackageReference Include="AutoCAD.NET" Version="$(AutoCADApiVersion)" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
