<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>TeyPdfCad.AutoCAD</RootNamespace>
    <AssemblyName>TeyPdfCad.AutoCAD</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AutoCADApiVersion>24.1.51000</AutoCADApiVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TeyPdfCad.Core/TeyPdfCad.Core.csproj" />
    <PackageReference Include="AutoCAD.NET" Version="$(AutoCADApiVersion)" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
