<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>TeyPdfCad.Web.Api</RootNamespace>
    <AssemblyName>TeyPdfCad.Web.Api</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TeyPdfCad.Web/TeyPdfCad.Web.csproj" />
  </ItemGroup>
</Project>
